### ISSUE TITLE
Beacon doesn't work on cellular

### ISSUE THREAD

**Issue by NetOpWibby** [imperviousinc/impervious-ios#4] opened 2021-12-14 19:48 UTC
Currently, Beacon only resolves over wifi. With the VPN active, it also blocks Internet access in Safari.

I'm running this on an iPhone 13 Pro Max on iOS 15.1.1.

**Comment by buffrr** [comment] 2021-12-14 22:29
Thanks for reporting this issue hm its working on iPhone 12 Pro iOS 15.1. I'll look into this. In the meantime, you can disable the VPN by going to Settings -> VPN -> uncheck Connect on demand for Beacon DNS and disconnect it.

You can configure your device to use native DoH for now since you're using iOS 15. This is the DoH server the app is using right now `https://hs.dnssec.dev/dns-query` (you can use any DoH server with handshake support but this one supports HIP-5)

**Comment by NetOpWibby** [comment] 2021-12-14 22:35
Where do I set the DoH server in iOS?

**Comment by buffrr** [comment] 2022-01-03 12:41
I was able to reproduce this issue on some cellular networks. It appears that carriers are increasingly becoming IPv6 only, and they support IPv4 using NAT64/DNS64. So they synthesize an AAAA record for websites that only support IPv4. Since the VPN operates on a very low level and doesn't use the carrier DNS server, it needs to detect such networks and synthesize answers when needed.

> Where do I set the DoH server in iOS?

You can use an app like DNSSecure which can generate a DoH profile or use this [profile generator](https://dns.notjakob.com/) but there'll be an update coming shortly.

**Comment by buffrr** [comment] 2022-01-06 22:05
@NetOpWibby version 1.0.1 is now available on the app store can you confirm the issue was fixed. Thanks!

**Comment by NetOpWibby** [comment] 2022-01-06 22:21
It is, nice! I'm also able to visit other sites no problem in Safari. Just some questions...

In Beacon's settings, I have System DNS activated and the DNS Server is set to `https://hs.dnssec.dev/dns-query`. Are these the defaults? Because, I wasn't getting resolution if I disabled System DNS and set the DOH Server to Beacon.

**Comment by buffrr** [comment] 2022-01-10 17:56
You can set DoH server to Beacon it currently points to `https://hs.dnssec.dev/dns-query` yeah. If you disable System DNS though, your device and the browser won't resolve HNS. So only disable it if you have configured your device to resolve HNS some other way.

**Comment by buffrr** [comment] 2022-01-10 18:07
Closing this fixed in ee21fb85c6c7803f4df3d64f1c409c12d4731a07. Thanks!

**Closed as completed by buffrr** 2022-01-10 18:07 UTC
